- name: Create .github directory
  ansible.builtin.file:
    path: "{{ repo_path }}/.github"
    state: directory

- name: Generate SECURITY.md file
  ansible.builtin.template:
    src: ./templates/SECURITY.md.j2
    dest: "{{ repo_path }}/.github/SECURITY.md"

- name: Generate LICENSE file
  ansible.builtin.template:
    src: "{{ './templates/licenses/' + repo.license + '.md.j2' }}"
    dest: "{{ repo_path }}/LICENSE"

- name: Generate .github/settings.yml
  ansible.builtin.template:
    src: ./templates/.github/settings.yml.j2
    dest: "{{ repo_path }}/.github/settings.yml"

- name: Generate .github/workflows directory
  ansible.builtin.file:
    path: "{{ repo_path }}/.github/workflows"
    state: directory

- when: repo.github.default_branch_push_protection
  name: "disable workflows incompatible with {{ repo.github.default_branch }} branch push protection"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ repo_path }}/.github/workflows/repo-ansible.yaml"
    - "{{ repo_path }}/.github/workflows/dependabot-auto-merge.yaml"

- when: not repo.github.default_branch_push_protection
  block:
  - name: Generate repo-ansible workflow
    ansible.builtin.copy:
      src: ./templates/.github/workflows/repo-ansible.yaml
      dest: "{{ repo_path }}/.github/workflows/repo-ansible.yaml"

  - name: Generate dependabot automerge workflow
    ansible.builtin.copy:
      src: ./templates/.github/workflows/dependabot-auto-merge.yaml
      dest: "{{ repo_path }}/.github/workflows/dependabot-auto-merge.yaml"
    when: repo.github.features.dependabot_auto_merge

- name: Generate CODEOWNERS file
  template:
    src: ./templates/CODEOWNERS.j2
    dest: "{{ repo_path }}/.github/CODEOWNERS"
  vars:
    codeowners: "{{ repo.codeowners }}"

- name: Generate CODE_OF_CONDUCT file
  template:
    src: "./templates/CODE_OF_CONDUCT.md.j2"
    dest: "{{ repo_path }}/.github/CODE_OF_CONDUCT.md"

- name: Generate CONTRIBUTING file
  template:
    src: "./templates/CONTRIBUTING.md.j2"
    dest: "{{ repo_path }}/CONTRIBUTING.md"
  when: "'CONTRIBUTING.md' not in repo.omit_files"

- name: generate README.md file
  ansible.builtin.template:
    src: ./templates/README.md.j2
    dest: "{{ repo_path }}/README.md"
  when: repo.readme.enable_generation

- when: repo.github.workflows.review
  block:
  - name: find workflow extensions
    ansible.builtin.command: "./library/list_extension_workflows.py '{{ repo_path }}'"
    register: extension_workflows
    changed_when: false

  - name: copy github review workflow
    ansible.builtin.template:
      src: ./templates/.github/workflows/10-review.yaml.j2
      dest: "{{ repo_path }}/.github/workflows/10-review.yaml"
      variable_start_string: '[['
      variable_end_string: ']]'
    vars:
      followup_workflows: "{{ extension_workflows.stdout | from_json }}"
      workflow_group: "10"
