# {{ repo_managed }}

FROM {{ repo.devcontainer.repository }}:{{ repo.devcontainer.tag }}

ENV APP_ENV=dev

ARG PACKAGIST_USER
ARG PACKAGIST_TOKEN

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG DEBIAN_FRONTEND=noninteractive

# - Install sudo, curl
# - Create a non-root user with the specified UID and GID
RUN apt-get update \
    && apt-get install -y \
    sudo \
    curl \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && sudo chsh -s /bin/bash ${USERNAME}

# - Install reviewdog
RUN curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s \
    && mv ./bin/reviewdog /usr/local/bin

WORKDIR /app

{% include './Dockerfile.d/apt-packages.j2' %}

{% include './Dockerfile.d/php-all.j2' %}

{% include './Dockerfile.d/php.j2' %}

{% include './Dockerfile.d/ansible.j2' %}

COPY --chown=${USERNAME}:${USERNAME} ../ /app

USER root