# {{ repo_managed }}

FROM {{ repo.docker.repository }}:{{ repo.docker.tag }}

EXPOSE 80

ENV APP_ENV=prod

COPY --chown=www-data:www-data . /app

WORKDIR /app

USER www-data

{% if repo.php['private-packagist'] %}
ARG PACKAGIST_TOKEN
ARG PACKAGIST_USER
RUN /usr/bin/composer config --global --auth http-basic.repo.packagist.com "$PACKAGIST_USER" "$PACKAGIST_TOKEN"
{% endif %}

RUN COMPOSER_MEMORY_LIMIT=-1 /usr/bin/composer install --no-scripts --no-dev

{% if repo.php['webpack-encore'] %}
RUN npm install && node_modules/.bin/encore production && rm -rf node_modules
{% endif %}

USER root

ENTRYPOINT ["apache2-foreground"]