# Managed by https://github.com/linkorb/repo-ansible. Manual changes will be overwritten.
name: Review

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
  workflow_call:

jobs:
  commit-conventions:
    runs-on: ubuntu-latest
    # Don't enforce commit conventions checks for Dependabot
    if: github.actor != 'dependabot[bot]'
    continue-on-error: true
    steps:
        # v6 https://github.com/actions/checkout/commit/de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      # interesting alternative: https://github.com/cocogitto/cocogitto
        # v1.3.0 https://github.com/webiny/action-conventional-commits/commit/8bc41ff4e7d423d56fa4905f6ff79209a78776c7
      - uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7

      - name: Check Card# reference
        # v1 https://github.com/linkorb/commit-message-checker/commit/dc804b50ce575a720739ec3f0ef3d5030130ec98
        uses: linkorb/commit-message-checker@dc804b50ce575a720739ec3f0ef3d5030130ec98
        with:
          # Matches lines that end in a card number:                  #1234
          # Matches lines that end in a card number and PR reference: #1234 (#20)
          pattern: '#\d{4,5}(\s+\(#\d+\))?'
          flags: 'gm'
          error: 'Your commit message has to end with a card number like "#1234".'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true

